/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountName = string;
export type AppError = { 'other' : string } |
  { 'invalidSession' : null } |
  { 'userAlreadyExists' : null } |
  { 'notAuthenticated' : null } |
  { 'weakPassword' : null } |
  { 'invalidCredentials' : null } |
  { 'invalidAccountName' : null };
export type Nickname = string;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Weather {
  'lat' : number,
  'lon' : number,
  'timezone' : string,
  'tempMax' : number,
  'tempMin' : number,
  'cityName' : string,
  'windSpeed' : number,
  'currentTemp' : number,
  'humidity' : bigint,
  'feelsLike' : number,
  'weatherCode' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAccount' : ActorMethod<
    [AccountName, Nickname, string],
    [] | [AppError]
  >,
  'getActorId' : ActorMethod<[string], [] | [AppError]>,
  'getAllUsers' : ActorMethod<
    [],
    { 'accountCount' : bigint, 'sessionCount' : bigint, 'userCount' : bigint }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentAccount' : ActorMethod<[string], [] | [AppError]>,
  'getWeather' : ActorMethod<[Principal, string, string], Weather>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isLoggedIn' : ActorMethod<[string], boolean>,
  'loginWithAccountName' : ActorMethod<[AccountName, string], [] | [AppError]>,
  'logout' : ActorMethod<[string], [] | [AppError]>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateNickname' : ActorMethod<[Nickname, string], [] | [AppError]>,
  'verifyCredentials' : ActorMethod<[AccountName, string], [] | [AppError]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];