/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AccountName = IDL.Text;
export const Nickname = IDL.Text;
export const AppError = IDL.Variant({
  'other' : IDL.Text,
  'invalidSession' : IDL.Null,
  'userAlreadyExists' : IDL.Null,
  'notAuthenticated' : IDL.Null,
  'weakPassword' : IDL.Null,
  'invalidCredentials' : IDL.Null,
  'invalidAccountName' : IDL.Null,
});
export const Weather = IDL.Record({
  'lat' : IDL.Float64,
  'lon' : IDL.Float64,
  'timezone' : IDL.Text,
  'tempMax' : IDL.Float64,
  'tempMin' : IDL.Float64,
  'cityName' : IDL.Text,
  'windSpeed' : IDL.Float64,
  'currentTemp' : IDL.Float64,
  'humidity' : IDL.Nat,
  'feelsLike' : IDL.Float64,
  'weatherCode' : IDL.Int,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAccount' : IDL.Func(
      [AccountName, Nickname, IDL.Text],
      [IDL.Opt(AppError)],
      [],
    ),
  'getActorId' : IDL.Func([IDL.Text], [IDL.Opt(AppError)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [
        IDL.Record({
          'accountCount' : IDL.Nat,
          'sessionCount' : IDL.Nat,
          'userCount' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentAccount' : IDL.Func([IDL.Text], [IDL.Opt(AppError)], ['query']),
  'getWeather' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [Weather], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isLoggedIn' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'loginWithAccountName' : IDL.Func(
      [AccountName, IDL.Text],
      [IDL.Opt(AppError)],
      [],
    ),
  'logout' : IDL.Func([IDL.Text], [IDL.Opt(AppError)], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateNickname' : IDL.Func([Nickname, IDL.Text], [IDL.Opt(AppError)], []),
  'verifyCredentials' : IDL.Func(
      [AccountName, IDL.Text],
      [IDL.Opt(AppError)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AccountName = IDL.Text;
  const Nickname = IDL.Text;
  const AppError = IDL.Variant({
    'other' : IDL.Text,
    'invalidSession' : IDL.Null,
    'userAlreadyExists' : IDL.Null,
    'notAuthenticated' : IDL.Null,
    'weakPassword' : IDL.Null,
    'invalidCredentials' : IDL.Null,
    'invalidAccountName' : IDL.Null,
  });
  const Weather = IDL.Record({
    'lat' : IDL.Float64,
    'lon' : IDL.Float64,
    'timezone' : IDL.Text,
    'tempMax' : IDL.Float64,
    'tempMin' : IDL.Float64,
    'cityName' : IDL.Text,
    'windSpeed' : IDL.Float64,
    'currentTemp' : IDL.Float64,
    'humidity' : IDL.Nat,
    'feelsLike' : IDL.Float64,
    'weatherCode' : IDL.Int,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAccount' : IDL.Func(
        [AccountName, Nickname, IDL.Text],
        [IDL.Opt(AppError)],
        [],
      ),
    'getActorId' : IDL.Func([IDL.Text], [IDL.Opt(AppError)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [
          IDL.Record({
            'accountCount' : IDL.Nat,
            'sessionCount' : IDL.Nat,
            'userCount' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentAccount' : IDL.Func([IDL.Text], [IDL.Opt(AppError)], ['query']),
    'getWeather' : IDL.Func([IDL.Principal, IDL.Text, IDL.Text], [Weather], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isLoggedIn' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'loginWithAccountName' : IDL.Func(
        [AccountName, IDL.Text],
        [IDL.Opt(AppError)],
        [],
      ),
    'logout' : IDL.Func([IDL.Text], [IDL.Opt(AppError)], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateNickname' : IDL.Func([Nickname, IDL.Text], [IDL.Opt(AppError)], []),
    'verifyCredentials' : IDL.Func(
        [AccountName, IDL.Text],
        [IDL.Opt(AppError)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };